descriptor-schema-version: "2.8"

info:
  name: modbusapp
  description: "Simple Docker Style app that streams RAW GPS data to a WebServer from IR1101"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: aarch64
  type: docker
  resources:
    profile: exclusive
    network:
      -
        interface-name: eth0
        ports:
            tcp: [8883]


# Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["python", "/app.py"]
